import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "../globals.css";
import Menu from "@/components/layouts/Menu";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} bg-background`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
